adlist.o: ds/adlist.c ds/adlist.h ds/zmalloc.h
ae.o: event/ae.c event/ae.h ds/zmalloc.h config.h event/ae_kqueue.c event/ae_epoll.c event/ae_select.c event/ae_evport.c
ae_epoll.o: event/ae_epoll.c
ae_evport.o: event/ae_evport.c
ae_kqueue.o: event/ae_kqueue.c
ae_select.o: event/ae_select.c
anet.o: io/anet.c fmacros.h io/anet.h
aof.o: persistent/aof.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h io/bio.h
bio.o: io/bio.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h io/bio.h
bitops.o: bitops.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h
blocked.o: blocked.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h
cluster.o: cluster/cluster.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h cluster/cluster.h endianconv.h
config.o: config.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h cluster/cluster.h
crc16.o: crc16.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h
crc64.o: crc64.c
db.o: persistent/db.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h cluster/cluster.h
debug.o: debug.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h sha1.h crc64.h io/bio.h
dict.o: ds/dict.c fmacros.h ds/dict.h ds/zmalloc.h redisassert.h
endianconv.o: endianconv.c
hyperloglog.o: ds/hyperloglog.c redis.h fmacros.h config.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h \
 ds/adlist.h ds/zmalloc.h io/anet.h codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h \
 rio.h
intset.o: codec/intset.c codec/intset.h ds/zmalloc.h endianconv.h config.h
lzf_c.o: lzf_c.c lzfP.h
lzf_d.o: lzf_d.c lzfP.h
memtest.o: memtest.c config.h
multi.o: multi.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h
networking.o: networking.c redis.h fmacros.h config.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h \
 ds/adlist.h ds/zmalloc.h io/anet.h codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h \
 rio.h
notify.o: notify.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h
object.o: ds/object.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h
pqsort.o: pqsort.c
pubsub.o: ds/pubsub.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h
rand.o: rand.c
rdb.o: persistent/rdb.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h lzf.h codec/zipmap.h \
 endianconv.h
redis-benchmark.o: redis-benchmark.c fmacros.h event/ae.h \
 ../deps/hiredis/hiredis.h ds/sds.h ds/adlist.h ds/zmalloc.h
redis-check-aof.o: redis-check-aof.c fmacros.h config.h
redis-check-dump.o: redis-check-dump.c lzf.h crc64.h
redis-cli.o: redis-cli.c fmacros.h version.h ../deps/hiredis/hiredis.h \
 ds/sds.h ds/zmalloc.h ../deps/linenoise/linenoise.h help.h io/anet.h event/ae.h
redis.o: redis.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h cluster/cluster.h slowlog.h \
 io/bio.h asciilogo.h
release.o: release.c release.h version.h crc64.h
replication.o: cluster/replication.c redis.h fmacros.h config.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h \
 ds/adlist.h ds/zmalloc.h io/anet.h codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h \
 rio.h
rio.o: rio.c fmacros.h rio.h ds/sds.h util.h crc64.h config.h redis.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h event/ae.h ds/dict.h ds/adlist.h \
 ds/zmalloc.h io/anet.h codec/ziplist.h codec/intset.h version.h persistent/rdb.h
scripting.o: scripting.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h sha1.h rand.h \
 ../deps/lua/src/lauxlib.h ../deps/lua/src/lua.h ../deps/lua/src/lualib.h
sds.o: ds/sds.c ds/sds.h ds/zmalloc.h
sentinel.o: cluster/sentinel.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h \
 ../deps/hiredis/hiredis.h ../deps/hiredis/async.h \
 ../deps/hiredis/hiredis.h
setproctitle.o: setproctitle.c
sha1.o: sha1.c sha1.h config.h
slowlog.o: slowlog.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h slowlog.h
sort.o: sort.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h pqsort.h
syncio.o: syncio.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h
t_hash.o: ds/t_hash.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h
t_list.o: ds/t_list.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h
t_set.o: ds/t_set.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h
t_string.o: ds/t_string.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h
t_zset.o: ds/t_zset.c redis.h fmacros.h config.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h event/ae.h ds/sds.h ds/dict.h ds/adlist.h ds/zmalloc.h io/anet.h \
 codec/ziplist.h codec/intset.h version.h util.h persistent/rdb.h rio.h
util.o: util.c fmacros.h util.h ds/sds.h
ziplist.o: codec/ziplist.c ds/zmalloc.h util.h ds/sds.h codec/ziplist.h endianconv.h \
 config.h redisassert.h
zipmap.o: codec/zipmap.c ds/zmalloc.h endianconv.h config.h
zmalloc.o: ds/zmalloc.c config.h ds/zmalloc.h
